"use client";

import { AuditDataType } from "@/components/dashboard/DashboardClient";
import { Copy, Wand2, ArrowRight, Check } from "lucide-react";
import { useState } from "react";

type Props = {
  auditData: AuditDataType | null;
};

export default function RewriteLab({ auditData }: Props) {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  if (!auditData) return null;

  const copy = async (text?: string, index?: number) => {
    if (!text) return;

    await navigator.clipboard.writeText(text);

    if (typeof index === "number") {
      setCopiedIndex(index);

      setTimeout(() => {
        setCopiedIndex(null);
      }, 2000);
    }
  };

  const weakHeadline =
    "Generic messaging with weak urgency and low emotional pull.";

  const weakCTA =
    "Submit / Learn More / Get Started";

  const weakTrust =
    "Minimal trust reinforcement near decision moments.";

  const rewrites = [
    {
      title: "Headline Upgrade",
      before: weakHeadline,
      after:
        auditData.quickWins?.headlineFix ||
        "Clearer value-focused messaging generated by AI.",
    },
    {
      title: "CTA Upgrade",
      before: weakCTA,
      after:
        auditData.quickWins?.ctaFix ||
        "More persuasive call-to-action generated by AI.",
    },
    {
      title: "Trust Upgrade",
      before: weakTrust,
      after:
        auditData.quickWins?.trustFix ||
        "Stronger credibility messaging generated by AI.",
    },
  ];

  return (
    <div className="mt-10 animate-fadeUp">
      {/* HEADER */}
      <div className="mb-8">
        <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-blue-50 border border-blue-100 shadow-sm">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center">
            <Wand2 size={15} className="text-white" />
          </div>

          <p className="text-xs uppercase tracking-[0.15em] text-blue-700 font-semibold">
            AI Rewrite Laboratory
          </p>
        </div>

        <h3 className="text-3xl md:text-4xl font-bold text-slate-900 mt-6 leading-tight">
          Instant Before → After Conversion Improvements
        </h3>

        <p className="text-slate-600 mt-4 max-w-3xl leading-8 text-[15px] md:text-base">
          PageDoctor AI generated optimized persuasion rewrites for the
          highest-friction messaging areas detected during analysis.
        </p>
      </div>

      {/* CARDS */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {rewrites.map((item, i) => (
          <div
            key={i}
            className="group relative overflow-hidden bg-white border border-slate-200 rounded-[32px] p-6 shadow-sm hover:shadow-2xl hover:-translate-y-1 transition-all duration-500"
          >
            {/* BACKGROUND GLOW */}
            <div className="absolute top-0 right-0 w-[140px] h-[140px] bg-blue-100 blur-[80px] opacity-0 group-hover:opacity-100 transition-all duration-500 rounded-full"></div>

            <div className="relative z-10">
              {/* CARD HEADER */}
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-semibold text-slate-900">
                    {item.title}
                  </p>

                  <p className="text-xs text-slate-400 mt-1">
                    AI persuasion enhancement
                  </p>
                </div>

                <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center border border-blue-100">
                  <Wand2 size={16} className="text-blue-600" />
                </div>
              </div>

              {/* BEFORE */}
              <div className="mt-7">
                <p className="text-xs uppercase tracking-wide text-red-500 font-semibold">
                  Before
                </p>

                <div className="mt-3 rounded-2xl bg-slate-50 border border-slate-200 p-5 min-h-[120px] flex items-center">
                  <p className="text-slate-500 leading-7 text-sm md:text-[15px]">
                    {item.before}
                  </p>
                </div>
              </div>

              {/* ARROW */}
              <div className="flex justify-center py-5">
                <div className="w-11 h-11 rounded-full bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 flex items-center justify-center shadow-sm">
                  <ArrowRight className="text-blue-600" size={18} />
                </div>
              </div>

              {/* AFTER */}
              <div>
                <p className="text-xs uppercase tracking-wide text-blue-600 font-semibold">
                  After
                </p>

                <div className="mt-3 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100 p-5 min-h-[140px] flex items-center">
                  <p className="text-slate-900 font-medium leading-7 text-sm md:text-[15px]">
                    {item.after}
                  </p>
                </div>
              </div>

              {/* BUTTON */}
              <button
                onClick={() => copy(item.after, i)}
                className="mt-6 w-full h-12 rounded-2xl bg-gradient-to-r from-slate-900 to-slate-800 text-white font-medium flex items-center justify-center gap-2 hover:from-blue-600 hover:to-indigo-600 transition-all duration-300 shadow-lg hover:shadow-xl"
              >
                {copiedIndex === i ? (
                  <>
                    <Check size={16} />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy size={16} />
                    Copy Rewrite
                  </>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}